# Generated by Django 3.0.4 on 2020-04-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_ud',
            new_name='user_id',
        ),
    ]
